import React, {useState} from 'react';
import { Search,ShoppingCart,Globe2,Users,Package,GraduationCap,ThumbsUp,BarChart3,Bot,Code2,Radio,BookOpen,Play,Heart,Check,CheckCircle2,ArrowUpRight,FileCode2,Settings,Coins,TrendingUp,ShieldCheck,Menu,X,ChevronRight,Star,ChartNoAxesCombined } from 'lucide-react';
import {BrandMark,ActionButton,IconButton,MarketChart,Sparkline,PlatformBadge,HandNote,SectionHeading,ArrowRight,HeroAdContainer,AdBannerContainer,CoinGrowthArt,DocumentGearArt} from './ui';
import {navLinks,products,markets,theme} from './tokens';
const platforms=['MetaTrader 4','MetaTrader 5','cTrader','TradingView'];
export function Header(){
 const [open,setOpen]=useState(false);const [query,setQuery]=useState('');const [lang,setLang]=useState('EN');
 return <header className="relative z-30 border-b border-[#e9e8ff] bg-white/95"><div className="mx-auto max-w-[1500px] px-5 lg:px-8">
  <div className="flex min-h-[64px] items-center justify-between gap-4"><BrandMark/><form onSubmit={e=>{e.preventDefault();document.getElementById('featured')?.scrollIntoView({behavior:'smooth'});}} className="relative hidden md:flex w-full max-w-[500px]"><input aria-label="Search marketplace" className="w-full rounded-md border border-violet-200 bg-violet-50/70 px-4 py-2 pr-10 text-xs outline-none focus:ring-2 focus:ring-violet-300" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search indicators, experts, scripts, courses, signals ..."/><button aria-label="Search" className="absolute right-3 top-1/2 -translate-y-1/2 text-violet-800"><Search size={17}/></button></form>
  <div className="flex items-center gap-2 sm:gap-3"><button aria-label="Shopping cart, 0 items" className="relative text-[#18214d]"><ShoppingCart size={22}/><span className="absolute -right-2 -top-2 grid h-4 w-4 place-items-center rounded-full bg-red-500 text-[9px] font-bold text-white">0</span></button><ActionButton href="#join" kind="outline" className="hidden sm:inline-flex px-3 py-2">Log In</ActionButton><ActionButton href="#join" className="px-3 py-2">Sign Up</ActionButton><button onClick={()=>setLang(lang==='EN'?'FA':'EN')} className="flex items-center gap-1 text-xs font-semibold text-slate-800" aria-label="Change language"><Globe2 size={20}/>{lang}</button><button className="lg:hidden" aria-label="Toggle navigation" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div></div>
  <nav aria-label="Main navigation" className={`${open?'flex':'hidden'} lg:flex flex-col lg:flex-row justify-center gap-1 lg:gap-6 text-[11px] font-semibold text-[#20274c]`}>{navLinks.map(([label,href],i)=><a onClick={()=>setOpen(false)} className={`py-3 transition hover:text-violet-700 ${i===0?'border-b-2 border-violet-700 text-violet-700':''}`} key={label} href={href}>{label}</a>)}</nav>
 </div></header>
}
const metrics=[['5,000+','Active Traders',Users],['1,200+','Products',Package],['300+','Educators',GraduationCap],['98%','Customer Satisfaction',ThumbsUp]];
export function HeroSection(){return <section id="home" className="relative isolate overflow-hidden"><div className="absolute inset-0 -z-10" style={{backgroundImage:theme.heroGlow}}/><div className="mx-auto max-w-[1500px] px-5 pt-7 pb-5 lg:px-8 lg:pt-9"><div className="grid gap-4 lg:grid-cols-[44%_56%] lg:min-h-[350px] items-center">
  <div className="relative z-10"><p className="mb-3 text-[10px] font-extrabold tracking-[.17em] text-violet-700">ALL TOOLS YOU NEED FOR A BETTER TRADING JOURNEY</p><h1 className="text-[46px] font-black leading-[1.04] tracking-[-.055em] text-[#111328] sm:text-[57px] xl:text-[64px]">Trade Smarter.<br/><span className="text-violet-700">Grow Together.</span></h1><p className="mt-4 text-[14px] leading-[1.5] text-[#596482]"><b className="text-[#414b6c]">GreenOrRed is the all-in-one platform for traders.</b><br/>Buy &amp; sell indicators, expert advisors, scripts, courses, signals, keep your trading journal, and request custom tools — all in one place.</p><div className="mt-4 flex flex-wrap gap-3"><ActionButton className="min-w-[174px]" href="#featured">Explore Marketplace <ArrowRight size={17}/></ActionButton><ActionButton kind="outline" href="#education" className="min-w-[145px]"><span className="rounded-full bg-violet-700 p-1 text-white"><Play size={12} fill="currentColor"/></span>Watch Video</ActionButton></div>
  <div className="mt-7 grid max-w-[575px] grid-cols-2 gap-y-3 sm:grid-cols-4">{metrics.map(([value,label,Icon])=><div key={label} className="flex items-center gap-2 border-r border-[#e8e5f6] pr-2 last:border-0"><Icon className="shrink-0 text-violet-700" size={25} fill="#ede9fe"/><div><div className="text-[17px] font-extrabold text-violet-800">{value}</div><div className="text-[10px] leading-tight text-slate-500">{label}</div></div></div>)}</div></div>
  <div className="relative z-10 mt-4 h-[265px] min-w-0 sm:h-[345px] lg:mt-0 lg:h-[390px]" aria-label="GreenOrRed trading platform showcase">
   <div aria-hidden="true" className="pointer-events-none absolute inset-[7%_4%] rounded-[50%] bg-violet-100/60 blur-2xl"/>
   <img src="/assets/hero-composite.svg" alt="Trading platform showcase showing MetaTrader 4, MetaTrader 5, cTrader and TradingView badges, a chart laptop and a trading journal phone" className="absolute inset-0 z-10 h-full w-full object-contain object-center" loading="eager" fetchPriority="high"/>
   <a href="#journal" aria-label="Open the trading journal" className="absolute bottom-[5%] right-[6%] z-20 h-[12%] w-[16%] rounded-lg focus-visible:outline focus-visible:outline-2 focus-visible:outline-violet-600"/>
  </div></div></div></section>}
const tradingTools=[
 {id:'indicators',title:'Indicators',desc:'Professional indicators to analyze markets with precision.',icon:BarChart3,accent:'violet',type:'chart'},
 {id:'experts',title:'Experts & Strategies',desc:'Automated trading systems with verified EAs and strategy results.',icon:Bot,accent:'blue',type:'curve'},
 {id:'scripts',title:'Scripts & Utilities',desc:'Powerful scripts and utilities to simplify your trading.',icon:Settings,accent:'green',type:'scripts'},
 {id:'signals',title:'Trading Signals',desc:'Real-time trading signals from top traders and verified providers.',icon:Radio,accent:'red',type:'signals'}
];
const toolAccent={
 violet:{icon:'bg-gradient-to-br from-violet-600 to-indigo-600 text-white',ring:'bg-violet-50 text-violet-700 border-violet-100'},
 blue:{icon:'bg-gradient-to-br from-blue-600 to-blue-700 text-white',ring:'bg-violet-50 text-violet-700 border-violet-100'},
 green:{icon:'bg-gradient-to-br from-emerald-600 to-green-700 text-white',ring:'bg-violet-50 text-violet-700 border-violet-100'},
 red:{icon:'bg-gradient-to-br from-red-500 to-rose-600 text-white',ring:'bg-violet-50 text-violet-700 border-violet-100'}
};
function ToolPreview({type}) {
 if(type==='chart') return <div className="relative h-full overflow-hidden rounded-[12px] bg-[#071934]">
   <img src="/assets/indicator-preview.svg" alt="SuperTrend indicator chart preview" className="h-full w-full object-cover" loading="lazy"/>
   <div className="absolute left-3 top-3 rounded-lg bg-[#12274b]/95 px-2.5 py-2 text-white shadow">
    <div className="text-[10px] font-medium">SuperTrend</div><div className="text-[16px] font-black text-emerald-400">+3.23%</div>
   </div>
  </div>;
 if(type==='curve') return <div className="relative h-full overflow-hidden rounded-[12px] bg-[#071934]">
   <img src="/assets/ea-preview.svg" alt="Expert advisor performance curve" className="h-full w-full object-cover" loading="lazy"/>
   <div className="absolute right-3 top-3 rounded-lg bg-[#10233f]/95 px-3 py-2 text-[10px] text-slate-300 shadow">
    <div className="flex min-w-[112px] justify-between gap-3"><span>Win Rate</span><b className="text-emerald-400">68.5%</b></div>
    <div className="mt-1 flex justify-between gap-3"><span>Total Trades</span><b className="text-white">248</b></div>
    <div className="mt-1 flex justify-between gap-3"><span>Total P&amp;L</span><b className="text-emerald-400">+12.4%</b></div>
   </div>
  </div>;
 if(type==='scripts') return <div className="grid h-full grid-cols-2 gap-2 rounded-[12px] bg-[#061a30] p-3 text-white">
   <div className="rounded-lg bg-[#0c2945] p-2.5">
    <div className="text-[11px] font-bold">Trade Manager</div>
    <div className="mt-3 flex gap-2"><span className="rounded bg-emerald-500 px-4 py-1 text-[10px] font-bold">Buy</span><span className="rounded bg-rose-500/80 px-4 py-1 text-[10px] font-bold">Sell</span></div>
    <div className="mt-3 space-y-2 text-[9px] text-slate-300"><div className="flex items-center gap-1"><CheckCircle2 size={10} className="text-emerald-400"/>Draw CandleBox</div><div className="flex items-center gap-1"><CheckCircle2 size={10} className="text-emerald-400"/>OnNewBar()</div></div>
   </div>
   <div className="rounded-lg bg-[#0c2945] p-2.5">
    <div className="text-[11px] font-bold">Risk Calculator</div>
    <div className="mt-3 space-y-2 text-[9px] text-slate-300">
     <div className="flex items-center justify-between"><span>Position Size</span><b className="rounded bg-[#173657] px-2 py-1 text-white">1.00</b></div>
     <div className="flex items-center justify-between"><span>SL (pips)</span><b className="rounded bg-[#173657] px-2 py-1 text-white">50</b></div>
     <div className="flex items-center justify-between"><span>TP (pips)</span><b className="rounded bg-[#173657] px-2 py-1 text-white">100</b></div>
    </div>
   </div>
  </div>;
 const rows=[['EURUSD','+1.26%','Buy'],['XAUUSD','+0.83%','Buy'],['BTCUSD','-0.21%','Sell'],['NAS100','+0.44%','Buy']];
 return <div className="h-full rounded-[12px] bg-[#061a30] px-4 py-3 text-white">{rows.map(([symbol,pct,side],i)=><div key={symbol} className="grid grid-cols-[1fr_auto_65px] items-center gap-3 border-b border-white/5 py-1.5 last:border-0">
   <div className="text-[11px] font-bold">{symbol}</div>
   <div className={`text-[10px] font-bold ${pct.startsWith('-')?'text-red-400':'text-emerald-400'}`}>{pct}</div>
   <span className={`rounded-full px-2 py-1 text-center text-[9px] font-bold ${side==='Buy'?'bg-emerald-500/80':'bg-rose-500/75'}`}>{side}</span>
  </div>)}</div>;
}
export function CategoryCards(){return <section id="trading-tools" aria-label="Trading tools" className="mx-auto max-w-[1500px] px-5 pt-4 lg:px-8">
 <div className="rounded-xl border border-[#e6e8fb] bg-white/90 p-4 shadow-[0_5px_20px_rgba(38,28,90,.04)] sm:p-5">
  <div className="mb-4 flex items-end justify-between gap-4">
   <div><h2 className="text-[25px] font-black tracking-[-.03em] text-[#111329] sm:text-[29px]">Explore <span className="text-violet-700">Trading Tools</span></h2><p className="mt-0.5 text-[13px] text-[#5c6992] sm:text-[15px]">Everything you need for a smarter trading experience.</p></div>
   <a href="#featured" className="hidden items-center gap-2 text-[12px] font-bold text-violet-700 hover:underline sm:flex">View All Tools <ArrowRight size={17}/></a>
  </div>
  <div className="grid grid-cols-1 gap-3 md:grid-cols-2 xl:grid-cols-4">
   {tradingTools.map(({id,title,desc,icon:Icon,accent,type})=><article id={id} key={id} className="overflow-hidden rounded-xl border border-[#e4e6f6] bg-white shadow-[0_5px_16px_rgba(40,31,93,.06)]">
    <div className="h-[150px] p-2.5 pb-0"><ToolPreview type={type}/></div>
    <div className="relative min-h-[124px] p-4 pr-[72px]">
     <div className="flex items-start gap-3"><span className={`grid h-11 w-11 shrink-0 place-items-center rounded-xl ${toolAccent[accent].icon}`}><Icon size={25} strokeWidth={2.6}/></span><div><h3 className="text-[15px] font-black leading-tight text-[#111329]">{title}</h3><p className="mt-1 text-[11px] leading-[1.45] text-[#53618a]">{desc}</p></div></div>
     <a href={id==='signals'?'#signals':'#'+id} aria-label={`Open ${title}`} className={`absolute bottom-4 right-4 grid h-10 w-10 place-items-center rounded-full border transition hover:scale-105 hover:bg-violet-100 ${toolAccent[accent].ring}`}><ArrowRight size={19} strokeWidth={2.6}/></a>
    </div>
   </article>)}
  </div>
 </div>
</section>}

export function PromotionalBanners(){return <section className="mx-auto grid max-w-[1500px] gap-3 px-5 pt-3 lg:grid-cols-2 lg:px-8"><article id="affiliate" className="relative isolate min-h-[146px] overflow-hidden rounded-lg border border-orange-100 bg-gradient-to-r from-[#fff9f5] to-[#fff5ec] p-4"><div className="relative z-10 flex gap-3 sm:pr-[125px]"><Users size={43} className="shrink-0 text-orange-500"/><div className="min-w-0 flex-1"><h2 className="text-lg font-extrabold text-orange-600">Affiliate Program</h2><p className="text-xs text-slate-600">You build, we connect. Earn by sharing great tools.</p><div className="mt-3 grid grid-cols-2 gap-1 text-[10px] text-slate-600">{['High commission rates','Marketing resources','Real-time tracking','Grow together'].map(x=><span key={x} className="flex items-center gap-1"><CheckCircle2 size={13} className="shrink-0 text-orange-600"/>{x}</span>)}</div><div className="mt-3 flex justify-end"><ActionButton kind="orange" href="#affiliate">Join Affiliate Program <ArrowRight size={14}/></ActionButton></div></div><div className="pointer-events-none absolute bottom-7 right-0 hidden h-[105px] w-[160px] sm:block"><img src="/assets/affiliate-art.svg" alt="" className="h-full w-full object-contain"/></div></div></article><article id="custom-request" className="relative isolate min-h-[146px] overflow-hidden rounded-lg border border-blue-100 bg-gradient-to-r from-[#f2f6ff] to-[#eef4ff] p-4"><div className="relative z-10 flex gap-3 sm:pr-[105px]"><FileCode2 size={43} className="shrink-0 text-blue-600"/><div className="min-w-0 flex-1"><h2 className="text-lg font-extrabold text-blue-700">Custom Requests</h2><p className="text-xs text-slate-600">Need a specific indicator or EA? Submit your request.</p><div className="mt-3 grid gap-1 text-[10px] text-slate-600">{['Get it built by our team or the community','Competitive offers from verified developers','Track progress and communicate easily'].map(x=><span key={x} className="flex items-center gap-1"><CheckCircle2 size={13} className="shrink-0 text-blue-600"/>{x}</span>)}</div><div className="mt-2 flex items-center justify-between gap-2"><span aria-hidden="true" className="hidden sm:block"/><ActionButton kind="blue" href="#custom-request">Submit a Request <ArrowRight size={14}/></ActionButton></div></div><div className="pointer-events-none absolute right-0 top-1 hidden h-[105px] w-[145px] sm:block"><img src="/assets/custom-art.svg" alt="" className="h-full w-full object-contain"/></div></div></article></section>}
export function PlatformTrustBanner(){return <section className="mx-auto max-w-[1500px] px-5 pt-3 lg:px-8"><div className="flex flex-wrap items-center justify-between gap-x-4 gap-y-3 rounded-lg border border-[#dfe1fb] bg-white px-4 py-3 sm:px-7"><h2 className="text-[17px] font-black leading-tight tracking-tight text-[#171a2b]">Trade with the <span className="text-violet-700">Right Tools.</span><br/>Make Informed Decisions.</h2><div className="flex flex-wrap items-center gap-3 sm:gap-5">{platforms.map(x=><PlatformBadge key={x} name={x}/>)}</div><HandNote className="hidden text-sm lg:block">Multiple Platforms<br/>One Marketplace ↙</HandNote></div></section>}
export function FeaturedProducts(){const [tab,setTab]=useState('Top Rated'),[saved,setSaved]=useState([]),[count,setCount]=useState(0);return <section id="featured" className="min-w-0"><div className="mb-3 flex flex-wrap items-center gap-3"><SectionHeading>Featured Products</SectionHeading><div className="flex items-center rounded-md bg-violet-50 p-1">{['Top Rated','Best Sellers','New Arrivals'].map(x=><button key={x} className={`rounded px-2.5 py-1.5 text-[10px] font-semibold ${tab===x?'bg-white text-violet-700 shadow-sm':'text-slate-500'}`} onClick={()=>setTab(x)}>{x}</button>)}</div><a href="#featured" className="ml-auto text-[11px] font-semibold text-violet-700">View All →</a></div><div className="grid gap-2 sm:grid-cols-3">{products.map(p=><article key={p.name} className="min-w-0 overflow-hidden rounded-lg border border-[#e7e9f9] bg-white p-1.5 shadow-sm"><div className="relative h-[95px] overflow-hidden rounded-md"><MarketChart className="h-full w-full" compact/><span style={{background:p.accent}} className="absolute left-1 top-1 rounded px-2 py-1 text-[9px] font-bold text-white">{p.tag}</span><button aria-label={`Save ${p.name}`} onClick={()=>setSaved(s=>s.includes(p.name)?s.filter(x=>x!==p.name):[...s,p.name])} className="absolute right-1 top-1 text-white"><Heart size={16} fill={saved.includes(p.name)?'#ef4444':'transparent'}/></button><span className="absolute bottom-1 right-1 rounded bg-white px-1 text-[8px] font-bold">{p.platform}</span></div><div className="px-1 pt-1.5"><h3 className="truncate text-[11px] font-extrabold text-slate-900">{p.name}</h3><p className="text-[10px] text-slate-500">{p.sub}</p><div className="text-[12px] tracking-tight text-amber-500">★★★★★ <span className="text-[9px] text-slate-400">(124)</span></div><div className="flex items-center justify-between"><strong className="text-[16px] text-slate-900">${p.price}</strong><IconButton label={`Add ${p.name} to cart`} onClick={()=>setCount(x=>x+1)} className="h-8 w-8"><ShoppingCart size={14}/></IconButton></div></div></article>)}</div><p aria-live="polite" className="sr-only">{count} items added to cart in this preview</p></section>}
export function Testimonials(){return <section className="min-w-0"><SectionHeading more>What Traders Say</SectionHeading><div className="mt-3 rounded-lg border border-[#e7e9f9] bg-white p-4 shadow-sm"><div className="text-amber-500">★★★★★</div><blockquote className="mt-2 text-[12px] leading-relaxed text-slate-600">“Amazing platform! High quality products and a very supportive community. My trading has improved a lot.”</blockquote><div className="mt-3 flex items-center gap-2"><div className="grid h-8 w-8 place-items-center rounded-full bg-violet-200 text-xs font-bold text-violet-700">AT</div><span className="text-[11px]"><strong className="block text-slate-900">Alex T.</strong><span className="text-slate-500">Verified Customer</span></span></div></div><div className="mt-2 flex justify-center gap-1">{[0,1,2].map(i=><span key={i} className={`h-1.5 w-1.5 rounded-full ${i===0?'bg-violet-700':'bg-violet-200'}`}/>)}</div></section>}
export function ConversionCard(){return <aside id="join" className="rounded-lg bg-gradient-to-br from-violet-700 to-violet-900 p-5 text-white shadow-[0_8px_24px_#4b1d9a20]"><h2 className="text-lg font-extrabold">Join GreenOrRed Today</h2><ul className="mt-3 grid gap-2">{['Access premium trading tools','Learn from experts','Track your performance','Be part of a global trading community'].map(x=><li key={x} className="flex items-center gap-2 text-[11px]"><CheckCircle2 size={14} fill="white" className="text-violet-700"/>{x}</li>)}</ul><ActionButton kind="red" href="#join" className="mt-4 w-full">Create Free Account <ArrowRight size={15}/></ActionButton><p className="mt-2 text-center text-[10px] text-violet-200">No credit card required</p></aside>}
export function BrandTrustBar(){return <section className="mt-3 border-t border-[#e7e8f5] bg-white"><div className="mx-auto flex max-w-[1500px] flex-wrap items-center justify-between gap-3 px-5 py-4 lg:px-8"><span className="text-[11px] text-slate-500">Trusted by traders worldwide</span>{markets.map((x,i)=><span className="inline-flex items-center gap-1.5 text-[10px] font-semibold text-slate-500" key={x}><span className="grid h-5 w-5 place-items-center rounded-full bg-slate-100 text-[10px] text-slate-500">{['◕','◉','▥','◆','₿','◈','▥'][i]}</span>{x}</span>)}<HandNote className="hidden text-xs xl:block">Same Market<br/>More Opportunities ↗</HandNote></div></section>}
export function Footer(){return <footer className="border-t border-[#efeff9] bg-white"><div className="mx-auto flex max-w-[1500px] flex-wrap justify-between gap-2 px-5 py-4 text-[10px] text-slate-500 lg:px-8"><span>© GreenOrRed. All rights reserved.</span><span>Design preview · Product imagery and metrics are illustrative.</span><span>Trade Smarter. Together.</span></div></footer>}
