import React, {useState} from 'react';
import { Search,ShoppingCart,Globe2,Users,Package,GraduationCap,ThumbsUp,BarChart3,Bot,Code2,Radio,BookOpen,Play,Heart,Check,CheckCircle2,ArrowUpRight,FileCode2,Settings,Coins,TrendingUp,ShieldCheck,Menu,X,ChevronRight,Star,ChartNoAxesCombined } from 'lucide-react';
import {BrandMark,ActionButton,IconButton,MarketChart,Sparkline,PlatformBadge,HandNote,SectionHeading,ArrowRight,HeroAdContainer,AdBannerContainer,CoinGrowthArt,DocumentGearArt} from './ui';
import {navLinks,products,markets,theme} from './tokens';
const platforms=['MetaTrader 4','MetaTrader 5','cTrader','TradingView'];
export function Header(){
 const [open,setOpen]=useState(false);const [query,setQuery]=useState('');const [lang,setLang]=useState('EN');
 return <header className="relative z-30 border-b border-[#e9e8ff] bg-white/95"><div className="mx-auto max-w-[1500px] px-5 lg:px-8">
  <div className="flex min-h-[64px] items-center justify-between gap-4"><BrandMark/><form onSubmit={e=>{e.preventDefault();document.getElementById('featured')?.scrollIntoView({behavior:'smooth'});}} className="relative hidden md:flex w-full max-w-[500px]"><input aria-label="Search marketplace" className="w-full rounded-md border border-violet-200 bg-violet-50/70 px-4 py-2 pr-10 text-xs outline-none focus:ring-2 focus:ring-violet-300" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search indicators, experts, scripts, courses, signals ..."/><button aria-label="Search" className="absolute right-3 top-1/2 -translate-y-1/2 text-violet-800"><Search size={17}/></button></form>
  <div className="flex items-center gap-2 sm:gap-3"><button aria-label="Shopping cart, 0 items" className="relative text-[#18214d]"><ShoppingCart size={22}/><span className="absolute -right-2 -top-2 grid h-4 w-4 place-items-center rounded-full bg-red-500 text-[9px] font-bold text-white">0</span></button><ActionButton href="#join" kind="outline" className="hidden sm:inline-flex px-3 py-2">Log In</ActionButton><ActionButton href="#join" className="px-3 py-2">Sign Up</ActionButton><button onClick={()=>setLang(lang==='EN'?'FA':'EN')} className="flex items-center gap-1 text-xs font-semibold text-slate-800" aria-label="Change language"><Globe2 size={20}/>{lang}</button><button className="lg:hidden" aria-label="Toggle navigation" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div></div>
  <nav aria-label="Main navigation" className={`${open?'flex':'hidden'} lg:flex flex-col lg:flex-row justify-center gap-1 lg:gap-6 text-[11px] font-semibold text-[#20274c]`}>{navLinks.map(([label,href],i)=><a onClick={()=>setOpen(false)} className={`py-3 transition hover:text-violet-700 ${i===0?'border-b-2 border-violet-700 text-violet-700':''}`} key={label} href={href}>{label}</a>)}</nav>
 </div></header>
}
const metrics=[['5,000+','Active Traders',Users],['1,200+','Products',Package],['300+','Educators',GraduationCap],['98%','Customer Satisfaction',ThumbsUp]];
export function HeroSection(){return <section id="home" className="relative isolate overflow-hidden"><div className="absolute inset-0 -z-10" style={{backgroundImage:theme.heroGlow}}/><div className="mx-auto max-w-[1500px] px-5 pt-7 pb-5 lg:px-8 lg:pt-9"><div className="grid gap-4 lg:grid-cols-[44%_56%] lg:min-h-[350px] items-center">
  <div className="relative z-10"><p className="mb-3 text-[10px] font-extrabold tracking-[.17em] text-violet-700">ALL TOOLS YOU NEED FOR A BETTER TRADING JOURNEY</p><h1 className="text-[46px] font-black leading-[1.04] tracking-[-.055em] text-[#111328] sm:text-[57px] xl:text-[64px]">Trade Smarter.<br/><span className="text-violet-700">Grow Together.</span></h1><p className="mt-4 text-[14px] leading-[1.5] text-[#596482]"><b className="text-[#414b6c]">GreenOrRed is the all-in-one platform for traders.</b><br/>Buy &amp; sell indicators, expert advisors, scripts, courses, signals, keep your trading journal, and request custom tools — all in one place.</p><div className="mt-4 flex flex-wrap gap-3"><ActionButton className="min-w-[174px]" href="#featured">Explore Marketplace <ArrowRight size={17}/></ActionButton><ActionButton kind="outline" href="#education" className="min-w-[145px]"><span className="rounded-full bg-violet-700 p-1 text-white"><Play size={12} fill="currentColor"/></span>Watch Video</ActionButton></div>
  <div className="mt-7 grid max-w-[575px] grid-cols-2 gap-y-3 sm:grid-cols-4">{metrics.map(([value,label,Icon])=><div key={label} className="flex items-center gap-2 border-r border-[#e8e5f6] pr-2 last:border-0"><Icon className="shrink-0 text-violet-700" size={25} fill="#ede9fe"/><div><div className="text-[17px] font-extrabold text-violet-800">{value}</div><div className="text-[10px] leading-tight text-slate-500">{label}</div></div></div>)}</div></div>
  <HeroAdContainer className="mt-6 lg:mt-0" aria-label="Illustrative trading software showcase"><div className="absolute inset-x-[7%] inset-y-[5%] -z-10 rounded-[45%] bg-violet-100/60 blur-2xl"/><HandNote className="absolute right-0 top-0 z-20 hidden text-[17px] sm:block">Tools. Knowledge.<br/>Community. Success. ↙</HandNote>
   <div className="absolute left-[13%] right-[16%] top-[13%] h-[73%] rounded-xl border-[7px] border-[#1d2533] bg-[#101827] shadow-[0_18px_34px_#27325a30] sm:left-[18%] sm:right-[17%]"><div className="relative h-full overflow-hidden rounded-sm"><MarketChart className="h-full w-full"/><div className="absolute bottom-2 left-3 right-3 flex gap-2">{['Orders','Positions','Journal'].map(x=><span className="rounded bg-slate-800 px-2 py-1 text-[7px] text-slate-300" key={x}>{x}</span>)}</div></div><div className="absolute -bottom-[11px] -left-[7%] -right-[7%] h-[13px] rounded-b-[80%] bg-gradient-to-b from-slate-300 via-slate-400 to-slate-600 shadow-lg"/></div>
   <div className="absolute left-0 top-[26%] z-10 flex flex-col gap-1 rounded-xl bg-[#19243a]/95 p-2 shadow-xl sm:left-[4%]">{platforms.map(x=><div key={x} className="rounded-md bg-white/5 px-2 py-1 text-white"><PlatformBadge name={x}/></div>)}</div>
   <div className="absolute bottom-[4%] right-0 z-10 w-[24%] min-w-[105px] max-w-[145px] rounded-[23px] border-[6px] border-[#202735] bg-white p-2 shadow-[0_12px_26px_#21223b35]"><div className="mx-auto mb-2 h-[4px] w-8 rounded-full bg-[#172033]"/><div className="mb-2 text-center text-sm font-black italic"><span className="text-emerald-500">G</span><span className="text-violet-600">/</span><span className="text-red-500">R</span></div>{[['EURUSD','+1.26%'],['XAUUSD','+0.83%'],['BTCUSD','+2.15%'],['US30','-0.32%'],['NAS100','+1.05%']].map(([sym,val])=><div className="flex justify-between border-b border-slate-100 py-[6px] text-[8px] font-bold" key={sym}><span>{sym}</span><span className={val.startsWith('-')?'text-red-500':'text-emerald-600'}>{val}</span></div>)}<a href="#journal" className="mt-2 block rounded bg-violet-700 py-2 text-center text-[8px] font-bold text-white">Track Your Trades</a></div><HandNote className="absolute right-0 top-[35%] hidden translate-x-[3%] text-[14px] xl:block">Your Trading<br/>Journey Matters ↙</HandNote>
  </HeroAdContainer></div></div></section>}
const categories=[
 {id:'indicators',title:'Indicators',desc:'Powerful technical indicators for MT4, MT5, cTrader & TradingView.',icon:BarChart3,theme:'blue',action:'Browse Indicators',type:'chart'},
 {id:'experts',title:'Experts & Strategies',desc:'Automate your trading with verified EAs and strategies.',icon:Bot,theme:'green',action:'Browse EAs & Strategies',type:'curve'},
 {id:'scripts',title:'Scripts & Utilities',desc:'Simple tools. Big impact. Automate tasks, manage trades and save time.',icon:Code2,theme:'red',action:'Browse Scripts',type:'list'},
 {id:'education',title:'Education',desc:'Learn from top traders and industry professionals. Live or on-demand.',icon:GraduationCap,theme:'blue',action:'Explore Education',type:'video'},
 {id:'signals',title:'Trading Signals',desc:'Access high-performing signals (Pay Per View).',icon:Radio,theme:'red',action:'Explore Signals',type:'signals'}
];
const cardStyles={blue:'bg-[#f7f8ff] border-[#e0e7ff] text-blue-700',green:'bg-[#f1fdf9] border-[#d6f5e8] text-emerald-700',red:'bg-[#fff7f7] border-[#ffdddd] text-red-600'};
function CategoryPreview({type}){if(type==='chart'||type==='curve')return <div className={`h-[65px] rounded-md border border-white/70 ${type==='curve'?'bg-emerald-50':'bg-white'}`}><Sparkline seed={type==='curve'?1:0} className="h-full w-full"/></div>;if(type==='list')return <div className="grid h-[65px] content-center gap-1 rounded-md bg-white/70 px-2">{['Trade Management','Chart Utilities','Session Tools'].map(x=><div className="flex items-center gap-1 text-[9px] text-slate-700" key={x}><CheckCircle2 size={10} className="text-blue-600"/>{x}</div>)}</div>;if(type==='video')return <div className="relative h-[65px] overflow-hidden rounded-md"><MarketChart className="h-full"/><Play className="absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 rounded-full bg-violet-700 p-2 text-white" size={32} fill="currentColor"/></div>;return <div className="grid h-[65px] gap-1 rounded-md bg-white/80 p-1">{[['EURUSD','+82%'],['XAUUSD','+67%'],['NAS100','+54%']].map(([a,b])=><div key={a} className="flex items-center justify-between text-[9px]"><span className="text-slate-700">{a}</span><b className="text-emerald-600">{b}</b></div>)}</div>}
export function CategoryCards(){return <section aria-label="Marketplace categories" className="mx-auto max-w-[1500px] px-5 lg:px-8"><div className="grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-5">{categories.map(({id,title,desc,icon:Icon,theme:color,action,type})=><article id={id} key={id} className={`flex min-h-[220px] flex-col rounded-lg border p-3.5 shadow-[0_3px_12px_#2e245509] ${cardStyles[color]}`}><div className="mb-2 flex items-center gap-2"><Icon size={33} strokeWidth={2.4} className="shrink-0"/><h2 className="text-[14px] font-extrabold leading-tight">{title}</h2></div><p className="mb-2 min-h-[48px] text-[11px] leading-[1.4] text-[#4b5673]">{desc}</p><CategoryPreview type={type}/><a href="#featured" className="mt-auto flex items-center justify-center gap-2 rounded-md bg-white/75 px-1 py-2 text-[11px] font-bold hover:bg-white">{action}<ArrowRight size={14}/></a></article>)}</div></section>}
export function PromotionalBanners(){return <section className="mx-auto grid max-w-[1500px] gap-3 px-5 pt-3 lg:grid-cols-2 lg:px-8"><article id="affiliate" className="relative overflow-hidden rounded-lg border border-orange-100 bg-gradient-to-r from-[#fff9f5] to-[#fff5ec] p-4"><div className="flex gap-3"><Users size={43} className="shrink-0 text-orange-500"/><div className="min-w-0 flex-1"><h2 className="text-lg font-extrabold text-orange-600">Affiliate Program</h2><p className="text-xs text-slate-600">You build, we connect. Earn by sharing great tools.</p><div className="mt-3 grid grid-cols-2 gap-1 text-[10px] text-slate-600">{['High commission rates','Marketing resources','Real-time tracking','Grow together'].map(x=><span key={x} className="flex items-center gap-1"><CheckCircle2 size={13} className="shrink-0 text-orange-600"/>{x}</span>)}</div><div className="mt-3 flex justify-end"><ActionButton kind="orange" href="#affiliate">Join Affiliate Program <ArrowRight size={14}/></ActionButton></div></div><div className="absolute right-2 top-1 hidden opacity-50 sm:block"><CoinGrowthArt/></div></div></article><article id="custom-request" className="relative overflow-hidden rounded-lg border border-blue-100 bg-gradient-to-r from-[#f2f6ff] to-[#eef4ff] p-4"><div className="flex gap-3"><FileCode2 size={43} className="shrink-0 text-blue-600"/><div className="min-w-0 flex-1"><h2 className="text-lg font-extrabold text-blue-700">Custom Requests</h2><p className="text-xs text-slate-600">Need a specific indicator or EA? Submit your request.</p><div className="mt-3 grid gap-1 text-[10px] text-slate-600">{['Get it built by our team or the community','Competitive offers from verified developers','Track progress and communicate easily'].map(x=><span key={x} className="flex items-center gap-1"><CheckCircle2 size={13} className="shrink-0 text-blue-600"/>{x}</span>)}</div><div className="mt-2 flex items-center justify-between gap-2"><HandNote className="hidden text-sm sm:block">Turn Your Ideas<br/>Into Reality ↗</HandNote><ActionButton kind="blue" href="#custom-request">Submit a Request <ArrowRight size={14}/></ActionButton></div></div><div className="absolute right-0 top-1 hidden opacity-30 sm:block"><DocumentGearArt/></div></div></article></section>}
export function PlatformTrustBanner(){return <section className="mx-auto max-w-[1500px] px-5 pt-3 lg:px-8"><div className="flex flex-wrap items-center justify-between gap-x-4 gap-y-3 rounded-lg border border-[#dfe1fb] bg-white px-4 py-3 sm:px-7"><h2 className="text-[17px] font-black leading-tight tracking-tight text-[#171a2b]">Trade with the <span className="text-violet-700">Right Tools.</span><br/>Make Informed Decisions.</h2><div className="flex flex-wrap items-center gap-3 sm:gap-5">{platforms.map(x=><PlatformBadge key={x} name={x}/>)}</div><HandNote className="hidden text-sm lg:block">Multiple Platforms<br/>One Marketplace ↙</HandNote></div></section>}
export function FeaturedProducts(){const [tab,setTab]=useState('Top Rated'),[saved,setSaved]=useState([]),[count,setCount]=useState(0);return <section id="featured" className="min-w-0"><div className="mb-3 flex flex-wrap items-center gap-3"><SectionHeading>Featured Products</SectionHeading><div className="flex items-center rounded-md bg-violet-50 p-1">{['Top Rated','Best Sellers','New Arrivals'].map(x=><button key={x} className={`rounded px-2.5 py-1.5 text-[10px] font-semibold ${tab===x?'bg-white text-violet-700 shadow-sm':'text-slate-500'}`} onClick={()=>setTab(x)}>{x}</button>)}</div><a href="#featured" className="ml-auto text-[11px] font-semibold text-violet-700">View All →</a></div><div className="grid gap-2 sm:grid-cols-3">{products.map(p=><article key={p.name} className="min-w-0 overflow-hidden rounded-lg border border-[#e7e9f9] bg-white p-1.5 shadow-sm"><div className="relative h-[95px] overflow-hidden rounded-md"><MarketChart className="h-full w-full" compact/><span style={{background:p.accent}} className="absolute left-1 top-1 rounded px-2 py-1 text-[9px] font-bold text-white">{p.tag}</span><button aria-label={`Save ${p.name}`} onClick={()=>setSaved(s=>s.includes(p.name)?s.filter(x=>x!==p.name):[...s,p.name])} className="absolute right-1 top-1 text-white"><Heart size={16} fill={saved.includes(p.name)?'#ef4444':'transparent'}/></button><span className="absolute bottom-1 right-1 rounded bg-white px-1 text-[8px] font-bold">{p.platform}</span></div><div className="px-1 pt-1.5"><h3 className="truncate text-[11px] font-extrabold text-slate-900">{p.name}</h3><p className="text-[10px] text-slate-500">{p.sub}</p><div className="text-[12px] tracking-tight text-amber-500">★★★★★ <span className="text-[9px] text-slate-400">(124)</span></div><div className="flex items-center justify-between"><strong className="text-[16px] text-slate-900">${p.price}</strong><IconButton label={`Add ${p.name} to cart`} onClick={()=>setCount(x=>x+1)} className="h-8 w-8"><ShoppingCart size={14}/></IconButton></div></div></article>)}</div><p aria-live="polite" className="sr-only">{count} items added to cart in this preview</p></section>}
export function Testimonials(){return <section className="min-w-0"><SectionHeading more>What Traders Say</SectionHeading><div className="mt-3 rounded-lg border border-[#e7e9f9] bg-white p-4 shadow-sm"><div className="text-amber-500">★★★★★</div><blockquote className="mt-2 text-[12px] leading-relaxed text-slate-600">“Amazing platform! High quality products and a very supportive community. My trading has improved a lot.”</blockquote><div className="mt-3 flex items-center gap-2"><div className="grid h-8 w-8 place-items-center rounded-full bg-violet-200 text-xs font-bold text-violet-700">AT</div><span className="text-[11px]"><strong className="block text-slate-900">Alex T.</strong><span className="text-slate-500">Verified Customer</span></span></div></div><div className="mt-2 flex justify-center gap-1">{[0,1,2].map(i=><span key={i} className={`h-1.5 w-1.5 rounded-full ${i===0?'bg-violet-700':'bg-violet-200'}`}/>)}</div></section>}
export function ConversionCard(){return <aside id="join" className="rounded-lg bg-gradient-to-br from-violet-700 to-violet-900 p-5 text-white shadow-[0_8px_24px_#4b1d9a20]"><h2 className="text-lg font-extrabold">Join GreenOrRed Today</h2><ul className="mt-3 grid gap-2">{['Access premium trading tools','Learn from experts','Track your performance','Be part of a global trading community'].map(x=><li key={x} className="flex items-center gap-2 text-[11px]"><CheckCircle2 size={14} fill="white" className="text-violet-700"/>{x}</li>)}</ul><ActionButton kind="red" href="#join" className="mt-4 w-full">Create Free Account <ArrowRight size={15}/></ActionButton><p className="mt-2 text-center text-[10px] text-violet-200">No credit card required</p></aside>}
export function BrandTrustBar(){return <section className="mt-3 border-t border-[#e7e8f5] bg-white"><div className="mx-auto flex max-w-[1500px] flex-wrap items-center justify-between gap-3 px-5 py-4 lg:px-8"><span className="text-[11px] text-slate-500">Trusted by traders worldwide</span>{markets.map((x,i)=><span className="inline-flex items-center gap-1.5 text-[10px] font-semibold text-slate-500" key={x}><span className="grid h-5 w-5 place-items-center rounded-full bg-slate-100 text-[10px] text-slate-500">{['◕','◉','▥','◆','₿','◈','▥'][i]}</span>{x}</span>)}<HandNote className="hidden text-xs xl:block">Same Market<br/>More Opportunities ↗</HandNote></div></section>}
export function Footer(){return <footer className="border-t border-[#efeff9] bg-white"><div className="mx-auto flex max-w-[1500px] flex-wrap justify-between gap-2 px-5 py-4 text-[10px] text-slate-500 lg:px-8"><span>© GreenOrRed. All rights reserved.</span><span>Design preview · Product imagery and metrics are illustrative.</span><span>Trade Smarter. Together.</span></div></footer>}
